# This workflow is a pipeline of multiple actions ,it is   triggered  for commits and pull on master branch

name: Building and publishing the Docker image

on:
  # triggered on push and pull_request on master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 
  build:
    # run the commands on ubuntu
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: geting the actor
        # getting the environment variable (the pseudo github of the actor)
        run: echo $GITHUB_ACTOR


      # verify that the repository  is under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
       
      - name: Build with maven
        run: mvn clean package
     
   
      - name: Building the Docker image
      
        run: |
           echo ${{ secrets.KEYAPT }} | docker login ghcr.io -u ChickenLivesMatter --password-stdin

           cd  docker/images/openliberty
           chmod 777 script.sh
           ./script.sh
           cd ../../../
           docker build -t stackover-goat/stackovergoat docker/images/openliberty
           docker tag stackover-goat/stackovergoat ghcr.io/amteam-heig/project_01/stackover-goat/stackovergoat:latest
           docker push ghcr.io/amteam-heig/project_01/stackover-goat/stackovergoat:latest


